with-expecter: false
dir: "{{.PackageName}}/testing"
filename: "{{.InterfaceName}}_mock_gen.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}testing"
packages:
  github.com/symflower/eval-dev-quality/language:
    interfaces:
      Language:
  github.com/symflower/eval-dev-quality/model:
    interfaces:
      Model:
  github.com/symflower/eval-dev-quality/provider:
    interfaces:
      Query:
