name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: make install

      - name: Install testing tools
        run: |
          make install-tools-testing
          echo "PATH=$HOME/.eval-dev-quality/bin:$PATH" >> $GITHUB_ENV

      - name: Lint Build
        run: make lint-build-ci

      - name: Test
        run: make test
